version: '3.8'

services:
  netloiter-ui-app:
    container_name: netloiter-ui-app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: ../
    environment:
      # Specifies the IP address of the host machine where NetLoiter is deployed.
      - NL_HOST_IP=192.168.64.4
      # Specifies the port number used for SSH communication on the NetLoiter host machine.
      - NL_HOST_PORT=22
      # Set to the username of a user with root permissions on the NetLoiter host machine.
      - NL_HOST_USERNAME=user
      # Set to the password associated with the specified username.
      - NL_HOST_PASSWORD=password
      # Set this environment variable to the path of the `netloiter.py` script on the NetLoiter host machine.
      - NL_PATH=~/Documents/NetLoiter/netloiter.py
      # Should be set to the directory path on the NetLoiter host machine where the configuration files will be uploaded.
      - NL_HOST_CONFIGS_PATH=~/Documents/NetLoiter
      # HOST_IP & DB_IP - Should both be set to the same IP of the machine on which the docker containers will be running.
      - HOST_IP=192.168.64.1
      - DB_IP=192.168.64.1
      - DB_PORT=5432
      - DATABASE_URL=postgresql://postgres:postgres@netloiter-ui-db:5432/netloiter_ui
      - FE_PORT=3000
      - BE_PORT=2022
    ports:
      - "3000:3000"
      - "2022:2022"
    depends_on:
      netloiter-ui-db:
        condition: service_healthy
    networks:
      netloiter_ui_network:
        ipv4_address: 10.5.0.3

  netloiter-ui-db:
    container_name: netloiter-ui-db
    build:
      dockerfile: ./docker/db/Dockerfile
      context: ../
    healthcheck:
      test: pg_isready -h localhost -d netloiter_ui
      interval: 5s
      retries: 10
    networks:
      netloiter_ui_network:
        ipv4_address: 10.5.0.4

networks:
  netloiter_ui_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
